---
apiVersion: v1
kind: Pod
metadata:
  name: vault-dynamic-secret-sidecar
spec:
  volumes:
  - name: secrets
    emptyDir: {}
  - name: vault-token
    emptyDir:
      medium: Memory

  initContainers:
  # The vault-authenticator container authenticates the container using the
  # kubernetes auth method and puts the resulting token on the filesystem.
  - name: vault-authenticator
    image: registry.hub.docker.com/anubhavmishra/vault-kubernetes-authenticator:0.2.0
    imagePullPolicy: Always
    volumeMounts:
    - name: vault-token
      mountPath: /home/vault
    env:
    - name: TOKEN_DEST_PATH
      value: /home/vault/.vault-token
    - name: VAULT_ADDR
      value: "http://vault:8200"
    - name: VAULT_ROLE
      value: gopher

  containers:
    # The consul-template container will pull secrets from Vault and expose
    # them as files on disk.
  - name: consul-template
    image: registry.hub.docker.com/sethvargo/consul-template:0.19.5.dev-alpine
    imagePullPolicy: Always
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
    - name: vault-token
      mountPath: /home/vault
    env:
    - name: HOME
      value: /home/vault
    - name: VAULT_ADDR
      value: "http://vault:8200"
    - name: CT_LOCAL_CONFIG
      value: |
        vault {
          retry {
            backoff = "1s"
          }
        }

        template {
          contents = <<EOH
            ---
            {{- with secret "database/creds/readonly" }}
            username: {{ .Data.username }}
            password: {{ .Data.password }}
            {{ end }}
          EOH
          destination = "/etc/secrets/config"
        }